export type Product = {
  id: string;
  slug: string;
  name: string;
  category: string;
  material: string;
  color: string;
  price: number;
  originalPrice?: number;
  rating: number;
  reviewCount: number;
  description: string;
  images: string[];
  stock: number;
  dimensions: string;
  weight: string;
  careInstructions: string;
  isFeatured?: boolean;
  isBestSeller?: boolean;
  isNewArrival?: boolean;
  highlights: string[];
};

export type Category = {
  name: string;
  slug: string;
  description: string;
  image: string;
};

const unsplash = (id: string, w = 1200, h = 1400) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&h=${h}&q=82`;

const craft = {
  diya:
    "https://imagescdn.jaypore.com/img/app/product/3/39733342-15721592.jpg?auto=format&w=900",
  diyaSet:
    "https://www.indianartvilla.in/cdn/shop/files/ALs6j_FPcaTw3jT4pulCemt_H_HlJMRz5D0fh-KCra9rsHP7cMFa-tnm3zx2TyB2ApIlrzHspCwunqZ0yypPzSOuZuFSaOxyBkH-YVZhrKcCOVtqZNAtVMj1hF3ZUmYHuA2A4EMPrskHoPj9cxCGR_bhQ-S18DO2n2QXSM_A4JG3oH_CFF317Gr_540x.jpg?v=1780553644",
  elephant:
    "https://www.rudhigat.com/pub/media/catalog/product/cache/5668f57f3959ea8ba6efa2386ebb2c3a/d/s/dsc06993_1.jpg",
  showcase: "https://shikhas.co/cdn/shop/files/handicraft-brand.png?v=1780937039&width=3200",
  display:
    "https://karukarjo.in/cdn/shop/articles/ChatGPT_Image_Aug_13_2025_09_30_19_AM.png?v=1755057826&width=1100",
  shelf:
    "https://cdn.shopify.com/s/files/1/0709/1522/7956/files/Handicrafts_Image_Jan_5_2026_02_05_23_PM.png?v=1767602490",
  brassBowls: "https://dukaan.b-cdn.net/700x700/webp/media/17bf711f-d65c-4882-918c-eee8494d92d5.png",
};

export const categories: Category[] = [
  {
    name: "Home Decor",
    slug: "home-decor",
    description: "Handcrafted accents that make everyday rooms feel collected.",
    image: craft.shelf,
  },
  {
    name: "Wooden Crafts",
    slug: "wooden-crafts",
    description: "Warm wood pieces carved, polished, and finished by hand.",
    image: craft.elephant,
  },
  {
    name: "Wall Decor",
    slug: "wall-decor",
    description: "Textural plates, hangings, and framed pieces for quiet drama.",
    image: craft.display,
  },
  {
    name: "Table Decor",
    slug: "table-decor",
    description: "Serveware and accents designed for gatherings and rituals.",
    image: unsplash("photo-1524758631624-e2822e304c36", 1200, 900),
  },
  {
    name: "Lamps & Lighting",
    slug: "lamps-lighting",
    description: "Softly glowing pieces for festive corners and evening homes.",
    image: unsplash("photo-1540932239986-30128078f3c5", 1200, 900),
  },
  {
    name: "Decorative Accessories",
    slug: "decorative-accessories",
    description: "Small details with craft, character, and a sense of place.",
    image: unsplash("photo-1602872030490-4a484a7b3ba6", 1200, 900),
  },
  {
    name: "Festive Collection",
    slug: "festive-collection",
    description: "Celebratory decor for festivals, weddings, and auspicious days.",
    image: craft.diya,
  },
  {
    name: "Gift Collection",
    slug: "gifts",
    description: "Thoughtful handcrafted gifts with a personal, lasting presence.",
    image: craft.showcase,
  },
];

export const spaceCollections = [
  { name: "Living Room", image: unsplash("photo-1600566753190-17f0baa2a6c3", 1100, 900) },
  { name: "Bedroom", image: unsplash("photo-1616594039964-ae9021a400a0", 1100, 900) },
  { name: "Dining", image: unsplash("photo-1616486338812-3dadae4b4ace", 1100, 900) },
  { name: "Entryway", image: unsplash("photo-1600210491892-03d54c0aaf87", 1100, 900) },
  { name: "Workspace", image: unsplash("photo-1518455027359-f3f8164ba6bd", 1100, 900) },
];

export const galleryImages = [
  unsplash("photo-1523413651479-597eb2da0ad6", 900, 900),
  unsplash("photo-1586023492125-27b2c045efd7", 900, 900),
  unsplash("photo-1598300042247-d088f8ab3a91", 900, 900),
  unsplash("photo-1600585154340-be6161a56a0c", 900, 900),
  unsplash("photo-1567016376408-0226e4d0c1ea", 900, 900),
  unsplash("photo-1616046229478-9901c5536a45", 900, 900),
];

export const products: Product[] = [
  {
    id: "p1",
    slug: "handcrafted-wooden-elephant-decor",
    name: "Handcrafted Wooden Elephant Decor",
    category: "Wooden Crafts",
    material: "Wood",
    color: "Walnut Brown",
    price: 1299,
    originalPrice: 1799,
    rating: 4.8,
    reviewCount: 86,
    description: "A finely carved wooden elephant accent inspired by traditional Indian motifs.",
    images: [craft.elephant, craft.display],
    stock: 14,
    dimensions: "18 x 8 x 14 cm",
    weight: "620 g",
    careInstructions: "Wipe with a dry cotton cloth. Keep away from standing water.",
    isFeatured: true,
    isBestSeller: true,
    highlights: ["Hand-carved surface", "Natural wood grain", "Gift-ready finish"],
  },
  {
    id: "p2",
    slug: "brass-diya-set",
    name: "Brass Diya Set",
    category: "Festive Collection",
    material: "Brass",
    color: "Antique Gold",
    price: 899,
    originalPrice: 1199,
    rating: 4.9,
    reviewCount: 124,
    description: "A set of traditional brass diyas for festive rituals and warm evening corners.",
    images: [craft.diya, craft.diyaSet],
    stock: 28,
    dimensions: "Each diya 7 x 7 x 3 cm",
    weight: "480 g",
    careInstructions: "Clean with a soft cloth. Use mild brass polish when required.",
    isBestSeller: true,
    highlights: ["Set of 4", "Traditional brass casting", "Festive packaging"],
  },
  {
    id: "p3",
    slug: "wooden-serving-tray",
    name: "Wooden Serving Tray",
    category: "Table Decor",
    material: "Wood",
    color: "Honey Teak",
    price: 1699,
    originalPrice: 2299,
    rating: 4.7,
    reviewCount: 62,
    description: "A generous serving tray with warm grain and hand-finished edges.",
    images: [unsplash("photo-1524758631624-e2822e304c36"), unsplash("photo-1533090481720-856c6e3c1fdc")],
    stock: 19,
    dimensions: "40 x 28 x 5 cm",
    weight: "950 g",
    careInstructions: "Do not soak. Wipe clean and occasionally oil the surface.",
    isFeatured: true,
    highlights: ["Food-safe finish", "Easy grip handles", "Hand-polished edges"],
  },
  {
    id: "p4",
    slug: "decorative-buddha-statue",
    name: "Decorative Buddha Statue",
    category: "Decorative Accessories",
    material: "Metal",
    color: "Aged Bronze",
    price: 2499,
    originalPrice: 3299,
    rating: 4.8,
    reviewCount: 47,
    description: "A serene Buddha statue for shelves, meditation corners, and console tables.",
    images: [craft.display, craft.shelf],
    stock: 9,
    dimensions: "16 x 12 x 24 cm",
    weight: "1.2 kg",
    careInstructions: "Dust gently with a soft dry brush or cloth.",
    isFeatured: true,
    highlights: ["Antique patina", "Balanced shelf scale", "Artisan finished"],
  },
  {
    id: "p5",
    slug: "hand-painted-wall-plate",
    name: "Hand-painted Wall Plate",
    category: "Wall Decor",
    material: "Ceramic",
    color: "Indigo Multi",
    price: 1199,
    rating: 4.6,
    reviewCount: 39,
    description: "A decorative ceramic wall plate with hand-painted Indian floral detailing.",
    images: [craft.showcase, craft.display],
    stock: 22,
    dimensions: "25 cm diameter",
    weight: "520 g",
    careInstructions: "Use a dry cloth only. Display hardware recommended.",
    isNewArrival: true,
    highlights: ["Hand-painted details", "Ready for wall display", "Contemporary color story"],
  },
  {
    id: "p6",
    slug: "macrame-wall-hanging",
    name: "Macrame Wall Hanging",
    category: "Wall Decor",
    material: "Natural Fibre",
    color: "Ivory",
    price: 1499,
    originalPrice: 1899,
    rating: 4.7,
    reviewCount: 54,
    description: "A soft natural-fibre wall hanging that brings texture to quiet rooms.",
    images: [unsplash("photo-1616046229478-9901c5536a45"), unsplash("photo-1616594039964-ae9021a400a0")],
    stock: 17,
    dimensions: "50 x 80 cm",
    weight: "700 g",
    careInstructions: "Shake lightly to remove dust. Spot clean only.",
    isBestSeller: true,
    highlights: ["Hand-knotted", "Natural cotton fibre", "Lightweight hanging"],
  },
  {
    id: "p7",
    slug: "wooden-jewellery-box",
    name: "Wooden Jewellery Box",
    category: "Gift Collection",
    material: "Wood",
    color: "Rosewood",
    price: 2199,
    originalPrice: 2799,
    rating: 4.9,
    reviewCount: 71,
    description: "A carved keepsake box for jewellery, letters, and meaningful small objects.",
    images: [craft.shelf, craft.showcase],
    stock: 11,
    dimensions: "22 x 15 x 9 cm",
    weight: "840 g",
    careInstructions: "Wipe dry. Avoid perfumes and direct moisture inside the box.",
    isFeatured: true,
    highlights: ["Velvet-feel lining", "Carved lid detail", "Premium gifting piece"],
  },
  {
    id: "p8",
    slug: "antique-candle-holder",
    name: "Antique Candle Holder",
    category: "Table Decor",
    material: "Metal",
    color: "Burnished Gold",
    price: 799,
    rating: 4.5,
    reviewCount: 33,
    description: "A compact candle holder with an aged finish for dinner tables and consoles.",
    images: [unsplash("photo-1540932239986-30128078f3c5"), unsplash("photo-1586023492125-27b2c045efd7")],
    stock: 31,
    dimensions: "9 x 9 x 12 cm",
    weight: "360 g",
    careInstructions: "Let wax cool before cleaning. Wipe with a soft cloth.",
    highlights: ["Aged metallic finish", "Stable weighted base", "Pairs beautifully"],
  },
  {
    id: "p9",
    slug: "handcrafted-table-lamp",
    name: "Handcrafted Table Lamp",
    category: "Lamps & Lighting",
    material: "Fabric",
    color: "Sage Green",
    price: 3499,
    originalPrice: 4299,
    rating: 4.8,
    reviewCount: 58,
    description: "A handcrafted lamp with a textile shade and warm ambient glow.",
    images: [unsplash("photo-1540932239986-30128078f3c5"), unsplash("photo-1600566753190-17f0baa2a6c3")],
    stock: 8,
    dimensions: "28 x 28 x 46 cm",
    weight: "1.8 kg",
    careInstructions: "Dust shade gently. Use LED bulb only.",
    isFeatured: true,
    isNewArrival: true,
    highlights: ["Soft textile shade", "Warm ambient light", "Statement bedside scale"],
  },
  {
    id: "p10",
    slug: "wooden-photo-frame",
    name: "Wooden Photo Frame",
    category: "Decorative Accessories",
    material: "Wood",
    color: "Natural Oak",
    price: 699,
    rating: 4.5,
    reviewCount: 42,
    description: "A handcrafted wooden frame for family photographs and art prints.",
    images: [unsplash("photo-1600210491892-03d54c0aaf87"), unsplash("photo-1505693416388-ac5ce068fe85")],
    stock: 36,
    dimensions: "Fits 5 x 7 inch photo",
    weight: "300 g",
    careInstructions: "Clean glass with a lint-free cloth. Keep frame dry.",
    highlights: ["Natural wood frame", "Tabletop or wall display", "Minimal profile"],
  },
  {
    id: "p11",
    slug: "decorative-vase",
    name: "Decorative Vase",
    category: "Home Decor",
    material: "Ceramic",
    color: "Matte Terracotta",
    price: 1899,
    originalPrice: 2399,
    rating: 4.7,
    reviewCount: 65,
    description: "A sculptural ceramic vase with an earthy matte finish.",
    images: [craft.showcase, craft.shelf],
    stock: 16,
    dimensions: "18 x 18 x 32 cm",
    weight: "1.1 kg",
    careInstructions: "Use for dried stems. Wipe with a damp cloth when needed.",
    isBestSeller: true,
    highlights: ["Matte ceramic finish", "Sculptural silhouette", "Ideal for dried stems"],
  },
  {
    id: "p12",
    slug: "traditional-toran",
    name: "Traditional Toran",
    category: "Festive Collection",
    material: "Fabric",
    color: "Marigold Multi",
    price: 999,
    rating: 4.6,
    reviewCount: 49,
    description: "A festive doorway toran with handcrafted textile and bead detailing.",
    images: [craft.showcase, craft.diya],
    stock: 24,
    dimensions: "95 x 18 cm",
    weight: "420 g",
    careInstructions: "Store flat in a dry pouch. Spot clean gently.",
    isNewArrival: true,
    highlights: ["Doorway ready", "Festive colors", "Hand-applied details"],
  },
  {
    id: "p13",
    slug: "brass-urli-bowl",
    name: "Brass Urli Bowl",
    category: "Festive Collection",
    material: "Brass",
    color: "Golden Brass",
    price: 2999,
    originalPrice: 3799,
    rating: 4.9,
    reviewCount: 92,
    description: "A classic brass urli bowl for flowers, floating candles, and festive styling.",
    images: [craft.brassBowls, craft.diya],
    stock: 12,
    dimensions: "30 cm diameter, 9 cm height",
    weight: "1.5 kg",
    careInstructions: "Dry after use. Polish occasionally to restore shine.",
    isFeatured: true,
    isBestSeller: true,
    highlights: ["Traditional urli form", "Solid brass feel", "Flower and candle styling"],
  },
  {
    id: "p14",
    slug: "handcrafted-coaster-set",
    name: "Handcrafted Coaster Set",
    category: "Table Decor",
    material: "Wood",
    color: "Mango Wood",
    price: 599,
    rating: 4.4,
    reviewCount: 28,
    description: "A set of wooden coasters with a simple carved border.",
    images: [unsplash("photo-1524758631624-e2822e304c36"), unsplash("photo-1533090481720-856c6e3c1fdc")],
    stock: 44,
    dimensions: "10 x 10 cm each",
    weight: "260 g",
    careInstructions: "Wipe dry after use. Do not put in dishwasher.",
    highlights: ["Set of 6", "Protective finish", "Everyday table accent"],
  },
  {
    id: "p15",
    slug: "wooden-wall-clock",
    name: "Wooden Wall Clock",
    category: "Wall Decor",
    material: "Wood",
    color: "Dark Walnut",
    price: 2699,
    originalPrice: 3299,
    rating: 4.6,
    reviewCount: 37,
    description: "A quiet wall clock with a hand-finished wooden dial and minimal markers.",
    images: [unsplash("photo-1505693416388-ac5ce068fe85"), unsplash("photo-1600210491892-03d54c0aaf87")],
    stock: 10,
    dimensions: "32 cm diameter",
    weight: "980 g",
    careInstructions: "Dust gently. Requires one AA battery.",
    isNewArrival: true,
    highlights: ["Silent movement", "Wooden dial", "Modern craft aesthetic"],
  },
  {
    id: "p16",
    slug: "elephant-sculpture",
    name: "Elephant Sculpture",
    category: "Home Decor",
    material: "Metal",
    color: "Antique Black",
    price: 1999,
    rating: 4.7,
    reviewCount: 44,
    description: "A compact elephant sculpture for entry consoles and bookshelf styling.",
    images: [craft.elephant, craft.display],
    stock: 15,
    dimensions: "24 x 9 x 16 cm",
    weight: "900 g",
    careInstructions: "Wipe with a dry cloth. Avoid abrasive cleaners.",
    isBestSeller: true,
    highlights: ["Symbolic elephant motif", "Aged hand finish", "Subtle statement scale"],
  },
  {
    id: "p17",
    slug: "carved-wooden-wall-panel",
    name: "Carved Wooden Wall Panel",
    category: "Wall Decor",
    material: "Wood",
    color: "Charcoal Wash",
    price: 4499,
    originalPrice: 5499,
    rating: 4.8,
    reviewCount: 26,
    description: "An ornate carved wall panel designed as a dramatic handmade focal point.",
    images: [craft.display, craft.shelf],
    stock: 6,
    dimensions: "60 x 90 x 4 cm",
    weight: "3.2 kg",
    careInstructions: "Dust with a soft brush. Install with proper wall anchors.",
    isFeatured: true,
    highlights: ["Large-format wall art", "Hand-carved relief", "Statement entryway piece"],
  },
  {
    id: "p18",
    slug: "ceramic-incense-holder",
    name: "Ceramic Incense Holder",
    category: "Decorative Accessories",
    material: "Ceramic",
    color: "Forest Green",
    price: 499,
    rating: 4.3,
    reviewCount: 31,
    description: "A compact ceramic holder for incense rituals and calming daily routines.",
    images: [unsplash("photo-1567016376408-0226e4d0c1ea"), unsplash("photo-1586023492125-27b2c045efd7")],
    stock: 52,
    dimensions: "22 x 4 x 2 cm",
    weight: "180 g",
    careInstructions: "Empty ash after each use. Hand wash only.",
    highlights: ["Ceramic glaze", "Ritual-ready form", "Small gift option"],
  },
  {
    id: "p19",
    slug: "woven-storage-basket",
    name: "Woven Storage Basket",
    category: "Home Decor",
    material: "Natural Fibre",
    color: "Natural Beige",
    price: 1599,
    originalPrice: 1999,
    rating: 4.6,
    reviewCount: 53,
    description: "A woven basket for throws, toys, planters, and warm storage moments.",
    images: [unsplash("photo-1598300042247-d088f8ab3a91"), unsplash("photo-1600566753190-17f0baa2a6c3")],
    stock: 18,
    dimensions: "35 x 35 x 32 cm",
    weight: "800 g",
    careInstructions: "Keep dry. Dust or vacuum with a brush attachment.",
    isNewArrival: true,
    highlights: ["Handwoven body", "Flexible storage", "Natural texture"],
  },
  {
    id: "p20",
    slug: "brass-bell-hanging",
    name: "Brass Bell Hanging",
    category: "Gift Collection",
    material: "Brass",
    color: "Antique Gold",
    price: 1399,
    rating: 4.7,
    reviewCount: 46,
    description: "A melodic brass bell hanging for balconies, pooja corners, and entryways.",
    images: [craft.diyaSet, craft.diya],
    stock: 21,
    dimensions: "12 x 12 x 45 cm",
    weight: "540 g",
    careInstructions: "Hang indoors or in covered areas. Wipe with a dry cloth.",
    isBestSeller: true,
    highlights: ["Hand-strung bells", "Warm antique finish", "Beautiful festive gift"],
  },
];

export const materials = ["Wood", "Brass", "Metal", "Fabric", "Ceramic", "Natural Fibre"];
export const colors = ["Walnut Brown", "Antique Gold", "Ivory", "Forest Green", "Matte Terracotta", "Natural Beige"];

export function formatPrice(value: number) {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(value);
}

export function getProduct(slug: string) {
  return products.find((product) => product.slug === slug);
}

export function getCategory(slug: string) {
  return categories.find((category) => category.slug === slug);
}

export function slugifyCategory(category: string) {
  return category.toLowerCase().replace(/&/g, "and").replace(/\s+/g, "-");
}

export function productsByCategory(categoryName: string) {
  return products.filter((product) => product.category === categoryName);
}
